// PANIM — render.js
// Builds the DOM for the intro-through-five-words reading experience from
// window.PANIM_CHAPTERS + window.PANIM_IMAGES (content/*.js — never mutated here).
// Exposes window.PANIM_RENDERED for motion.js / sync.js / player.js to consume.
// 11-website-plan.md §5, §6, §9, §10.

(function () {
  'use strict';

  var ROMAN = ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];

  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  function normTerm(s) {
    return String(s).trim().replace(/[.,;:]+$/, '').trim();
  }

  // Wraps the first exact-match occurrence of each chapter glossary term inside <em>…</em>
  // spans with a gloss-term span (§4.1 / C9). Trailing sentence punctuation inside the <em>
  // is tolerated (e.g. "<em>Panim.</em>" still matches term "Panim") — the match must still
  // be the WHOLE italic span, never a substring of a longer italic phrase, so running prose
  // is never corrupted. Terms with no exact italic match anywhere in the chapter are left
  // alone and reported via PANIM_RENDERED.skippedGlossTerms for BUILD-NOTES.
  function glossify(chapter) {
    var terms = (chapter.glossary || []).map(function (g) { return { term: g.term, gloss: g.gloss, norm: normTerm(g.term) }; });
    var used = {};
    var skipped = [];

    function applyToHtml(html) {
      return html.replace(/<em>([^<]*)<\/em>/g, function (whole, inner) {
        var n = normTerm(inner);
        for (var i = 0; i < terms.length; i++) {
          var t = terms[i];
          if (!used[t.term] && t.norm === n) {
            used[t.term] = true;
            return '<em class="gloss-term" tabindex="0" data-gloss-term="' + esc(t.term) + '" data-gloss-text="' + esc(t.gloss) + '">' + inner + '</em>';
          }
        }
        return whole;
      });
    }

    chapter.blocks.forEach(function (b) {
      if (b.type === 'p') b._html = applyToHtml(b._html);
    });

    terms.forEach(function (t) {
      if (!used[t.term]) skipped.push(chapter.id + ': "' + t.term + '"');
    });
    return skipped;
  }

  // Hebrew must be split by GRAPHEME, never by code point: פָּנִים carries combining
  // vowel points, and Array.from() would tear a nikkud mark off its consonant and
  // animate it as a separate glyph. Intl.Segmenter does this correctly; the regex
  // fallback keeps any combining mark (U+0590–U+05C7) attached to the letter before it.
  function hebGraphemes(str) {
    if (typeof Intl !== 'undefined' && Intl.Segmenter) {
      try {
        var seg = new Intl.Segmenter('he', { granularity: 'grapheme' });
        return Array.from(seg.segment(str), function (s) { return s.segment; });
      } catch (e) { /* fall through */ }
    }
    return str.match(/[\s\S][\u0591-\u05C7]*/g) || [str];
  }

  function hebSpans(str, delayStep) {
    return hebGraphemes(str).map(function (g, i) {
      var d = delayStep ? ' style="animation-delay:' + (i * delayStep) + 'ms"' : '';
      return '<span class="heb-g"' + d + '>' + esc(g) + '</span>';
    }).join('');
  }

  var PANIM_HEB = '\u05E4\u05B8\u05BC\u05E0\u05B4\u05D9\u05DD';  // פָּנִים

  // ---------- responsive art ----------
  // Every plate used to be served at its full width to every device: a 402px phone
  // downloaded a 1408px WebP and painted it at 402. content/derivatives.js is
  // GENERATED by tools/make-derivatives.sh and holds the AVIF cuts; the WebP stays
  // as the <img>, so a browser without AVIF is exactly as well off as before.
  // 🛑 The <img src> must stay the ORIGINAL full-width file. js/ui.js's lightbox
  // reads that attribute to show the picture full size, and the widths in `sizes`
  // are what the CSS actually gives the figure — change one, change the other.
  var PLATE_SIZES = '(min-width: 1440px) 1440px, 100vw';           // .plate / .hero-plate: shell-wide, breaking the page margin
  var SLOT_SIZES  = '(min-width: 901px) 660px, 92vw';              // .img-slot: 6 of 12 columns above the 900px breakpoint, full measure below

  function avifSource(slotId, sizes) {
    var set = window.PANIM_DERIVATIVES ? window.PANIM_DERIVATIVES[slotId] : null;
    if (!set || !set.length) return '';
    var srcset = set.map(function (d) { return esc(d.src) + ' ' + d.w + 'w'; }).join(', ');
    return '<source type="image/avif" srcset="' + srcset + '" sizes="' + esc(sizes) + '">';
  }

  function renderImageSlot(slotId) {
    var img = window.PANIM_IMAGES ? window.PANIM_IMAGES[slotId] : null;
    if (img && img.src) {
      // `ref` was authored on every image and rendered by renderPlate only, so the
      // five INLINE slots dropped it silently — ch01-scroll's "Numbers 6:24-26 -
      // c. 600 BC" had never once appeared. Same shape as the plate caption: the
      // caption says what it is, the ref says where you are.
      var cap = (img.caption || img.ref)
        ? '<figcaption>' + esc(img.caption || '') +
            (img.ref ? '<span class="slot-ref">' + esc(img.ref) + '</span>' : '') +
          '</figcaption>'
        : '';
      // WCAG 2.1.1: the slot opens a lightbox (js/ui.js wireLightbox) and used to do
      // it on a bare click listener only — no tabindex, no role, no keyboard path in
      // at all.
      // 🛑 A REAL <button>, NOT role="button" ON THE <figure>, 2026-08-29. It was
      // tabindex="0" role="button" on the figure itself, and axe-core rejects that
      // outright (aria-allowed-role): <figure> has an implicit role that cannot be
      // overridden, so the element was operable but the role was being discarded —
      // a control announcing itself as a figure. Round eleven's audit reported zero
      // violations here; a newer axe finds five, one per inline slot.
      // The button wraps the PICTURE only. It must not wrap the <figcaption>: the
      // caption is the figure's description, not part of the control's name, and
      // inside the button it would be read out as part of the label.
      return '<figure class="img-slot is-filled reveal" data-slot="' + esc(slotId) + '">' +
        '<button type="button" class="slot-open" aria-label="View larger: ' +
          esc(img.alt || 'image') + '">' +
          '<picture>' + avifSource(slotId, SLOT_SIZES) +
            '<img src="' + esc(img.src) + '" alt="' + esc(img.alt || '') + '" loading="lazy">' +
          '</picture>' +
        '</button>' + cap +
        '</figure>';
    }
    // An empty slot renders NOTHING, 2026-08-28. It used to draw a framed box with
    // the words "Image forthcoming" in it — a published book telling every reader
    // that two of its pictures are not done. A chapter without a plate should look
    // like a chapter without a plate: it opens on its title.
    return '';
  }

  // THE VERSE NOTE — the apparatus under a quotation.
  //
  // Looked up by CHAPTER + CITATION, never by block id: ids are assigned in
  // manuscript order by tools/build-chapters.py and move whenever a paragraph is
  // added or cut, which is the same reason cues have to be rebuilt after the
  // chapters are. A citation does not move. See content/verse-notes.js.
  //
  // It renders under the verse, in the reading column, not in the margin the
  // citation hangs in — that column is six steps wide and a sixty-word note set
  // in it is a ribbon, not a note. There is one apparatus system here and this
  // joins it rather than opening a second one.
  //
  // No entry, no note. That is deliberate: some quotations in the book are the
  // book echoing a verse it has already cited, and an apparatus line under those
  // would undo the echo.
  function renderVerseNote(chapterId, ref) {
    var all = window.PANIM_VERSE_NOTES;
    var n = all && all[chapterId] && ref ? all[chapterId][ref] : null;
    if (!n || (!n.where && !n.worth)) return '';
    // `where` and `worth` carry <em> for transliterations and quoted words, which
    // is authored content in a file that is not generated — so it is inserted as
    // markup, exactly as content/thread.js's notes already are.
    // role="note", NOT <aside> — see the note in css/components.css. 113 <aside>
    // elements are 113 "complementary" landmarks in the rotor, which is the opposite
    // of skippable. role="note" announces the apparatus without becoming a landmark.
    return '<div class="verse-note" role="note">' +
      (n.where ? '<p class="vn-line"><b class="vn-label">Where you are</b> ' + n.where + '</p>' : '') +
      (n.worth ? '<p class="vn-line"><b class="vn-label">Worth knowing</b> ' + n.worth + '</p>' : '') +
    '</div>';
  }

  function renderVerse(b, chapterId) {
    var lines = b.lines.map(function (l) { return '<span class="verse-line">' + esc(l) + '</span>'; }).join('');
    // Two quotations in ch. V carry no reference on purpose: they are the book
    // echoing a verse it has already cited, printed bare so the sentence lands
    // as a sentence. An empty apparatus line under them would undo that.
    var apparatus = '';
    if (b.ref) {
      var tag = (b.translation && b.translation !== 'NASB')
        ? '<span class="verse-translation">' + esc(b.translation) + '</span>' : '';
      // THE CITATION IS SET IN TWO VOICES, 2026-08-29. A reference is a name and a
      // number and they do not want the same typography: "Song of Songs" wants the
      // tracked small caps a running head gets, "2:14" wants tabular lining figures
      // and no tracking at all — uppercase letter-spacing on digits opens a gap
      // between the numeral and the colon and the reference stops reading as one
      // address. Split at the FIRST digit run that is not a book's own leading
      // numeral, so "1 Kings 19:11" keeps its 1 with the book while
      // "Psalm 88:14, 18" — the one compound reference in the book — is not cut
      // after the comma, which is what a greedy split does and how it would have
      // shipped. Verified against all 124 references in content/chapters.js.
      var m = /^((?:[1-3]\s)?[^0-9]+?)\s+([0-9].*)$/.exec(b.ref);
      var refInner = m
        // the literal space matters: the two spans are blocks in the margin and the
        // space collapses, but below 1100px they are inline and without it the
        // citation reads — and copies, and is announced — as "Numbers6:24-26".
        ? '<span class="vr-book">' + esc(m[1]) + '</span> ' +
          '<span class="vr-loc">' + esc(m[2]) + '</span>'
        : '<span class="vr-book">' + esc(b.ref) + '</span>';
      apparatus = '<div class="verse-ref"><span class="verse-ref-text">' +
        refInner + '</span>' + tag + '</div>';
    }
    return '<div class="verse-box reveal veil-lift" id="' + esc(b.id) + '" data-cue-id="' + esc(b.id) + '">' +
      '<span class="verse-quotemark" aria-hidden="true">&#8220;</span>' +
      '<div class="verse-text">' + lines + '</div>' +
      apparatus +
      renderVerseNote(chapterId, b.ref) +
      '</div>';
  }

  function renderFiveWords(b) {
    var words = b.text.split(' ').map(function (w) {
      return '<span class="fw-word">' + esc(w) + '</span>';
    }).join(' ');
    return '<section class="section" id="five-words" data-ch="fw">' +
      '<div class="section-inner">' +
      '<p class="fivewords-text" id="fivewords-text">' + words + '</p>' +
      '<span class="fivewords-ref" id="fivewords-ref">' + esc(b.ref) + '</span>' +
      '</div></section>';
  }

  // WHAT COMES BACK — the closing section, after the five words.
  //
  // It used to be a sheet behind a button in the running head: thirteen bare labels
  // and two chapter links, opened by a control that competed with About and Listen
  // before a first-time reader had read a sentence. At the end of the book the same
  // thirteen entries change job — they stop being navigation and become the argument.
  // Data and every claim in it live in content/thread.js.
  //
  // IT IS NOT CALLED "THE THREAD" ANY MORE. That was a working title borrowed from
  // the build brief and it named the mechanism rather than the thing: a reader who
  // has just finished the book does not need to be told there is a thread, they need
  // to be told what came back. The id stays `thread` — anchors, the stylesheet and
  // content/thread.js all key off it, and renaming an id to match a heading is how
  // links rot.
  //
  // EACH ENTRY IS A <details>, and that is not only for length. The thirteen notes
  // are a wall of thirteen paragraphs if they are all open, and — the reason it is
  // native rather than scripted — the summary now carries the numerals as TEXT and
  // the two chapter links have moved down into the body. Those links used to be
  // ~22px tall in a row whose baseline could not take padding, which failed WCAG 2.2
  // target size. In the body they are ordinary links with room to be 44px. The fix
  // and the feature are the same change.
  function renderThread() {
    var entries = window.PANIM_THREAD || [];
    if (!entries.length) return '';
    var rows = entries.map(function (t) {
      var fromN = +t.from.slice(2), toN = +t.to.slice(2);
      var from = ROMAN[fromN] || t.from, to = ROMAN[toN] || t.to;
      var lo = Math.min(fromN, toN), hi = Math.max(fromN, toN);
      // THE RAIL. Ten ticks, one per chapter, with the span drawn between the two
      // this entry connects. The whole point of the section is distance — planted
      // here, paid off there — and a rail says it at a glance where "IV → VI" made
      // you do the arithmetic. Every row's rail is on the same scale, so the eye
      // reads the shape of the book: the early plants reach further than the late.
      var ticks = '';
      for (var n = 1; n <= 10; n++) {
        var cls = 'thr-tick' +
          (n === fromN ? ' is-plant' : '') +
          (n === toN ? ' is-payoff' : '') +
          (n > lo && n < hi ? ' is-under' : '');
        ticks += '<i class="' + cls + '" style="--n:' + n + '"></i>';
      }
      var rail =
        '<span class="thread-rail" aria-hidden="true" style="--from:' + lo + ';--to:' + hi + '">' +
          '<span class="thr-bar"></span>' + ticks +
        '</span>' +
        '<span class="visually-hidden">Planted in chapter ' + from +
          ', paid off in chapter ' + to + '. </span>';
      // THE NUMERALS MOVED TO THE RIGHT END OF THE ROW, 2026-08-29 (decision D4-B).
      // They were stacked under the left of the rail, because hung from their own
      // ticks they collided outright on neighbouring chapters — VII → VIII set as
      // VIIVIII — and there is no positioning rule that fixes that for a scale this
      // narrow. Hard right they cannot collide with ticks they are no longer under,
      // and the row's 1325px rule stops being 900px of nothing: title left, leader
      // across, span right, which is what the Index of Scripture does one section
      // later and what the index of any printed book does. Two index-shaped sections,
      // one language.
      var legend =
        '<i class="thread-leader" aria-hidden="true"></i>' +
        '<span class="thr-legend" aria-hidden="true">' + from +
          '<i class="thr-to">&#8594;</i>' + to + '</span>';
      return '<details class="thread-item reveal">' +
        '<summary class="thread-summary">' +
          '<span class="thread-span">' + rail + '</span>' +
          '<span class="thread-head-body">' +
            '<h3 class="thread-name">' + t.label + '</h3>' + legend +
          '</span>' +
        '</summary>' +
        '<div class="thread-detail">' +
          '<p class="thread-note">' + t.note + '</p>' +
          (t.refs ? '<p class="thread-refs">' + esc(t.refs) + '</p>' : '') +
          '<p class="thread-jump">' +
            '<a href="#' + esc(t.from) + '">Chapter ' + from + '</a>' +
            '<a href="#' + esc(t.to) + '">Chapter ' + to + '</a>' +
          '</p>' +
        '</div>' +
      '</details>';
    }).join('');
    // THE STANDFIRST IS GONE, 2026-08-28. It carried a headline — "Nothing in this
    // book was set down once." — and three lines explaining that a thread only
    // reads as a thread once you have walked its whole length. Both were the
    // section apologising for itself at the end of a book the reader has just
    // finished. The section name is the heading now, and the rails do the
    // explaining the paragraph was doing.
    return '<section class="section" id="thread" data-ch="fw" aria-labelledby="thread-heading">' +
      '<div class="section-inner">' +
        '<div class="thread-head">' +
          '<h2 class="chapter-num" id="thread-heading">What Comes Back</h2>' +
          '<p class="thread-count">' + entries.length + ' threads</p>' +
        '</div>' +
        rows +
      '</div></section>';
  }

  // THE LEXICON — the closing plate, after the Thread.
  //
  // The words are set as REAL TEXT in Frank Ruhl Libre, not as images. A Hebrew
  // letterform is already a drawing; a picture of one is heavier, blurrier at the
  // size this wants, unselectable, invisible to a screen reader and needs a retina
  // twin. Everything below is done in CSS on live type.
  //
  // TWO THINGS HAPPEN TO EVERY WORD, in order, and they are the whole section:
  //
  //   1. IT DRAWS ITSELF. A feathered mask sweeps across the letters — right to
  //      left for Hebrew, the direction Hebrew is actually written; left to right
  //      for Greek, because Greek is — so the word is laid down by a nib rather
  //      than faded in. It runs at 2.6s, not the 1.5s it shipped at: a sweep fast
  //      enough to miss is just a transition, and the point is to watch it happen.
  //
  //   2. THE ROOT STAYS LIT. A beat after the word lands, everything that is not
  //      a root consonant dims — the vowel points, the prefixes, the vowel letters
  //      — and the root is left burning on the page. In a book about one word's
  //      biography this is the most on-theme move available, and it is why
  //      content/lexicon.js carries a `root` field at all.
  //
  // 🛑 THE ROOT MATCH FAILS SAFE. `root` holds the letters of the root ACTUALLY
  // PRESENT in this form, in order. hebClusters splits the word into base letters
  // with their points attached, then matches `root` as a subsequence of the base
  // letters only. No match, no highlight — a wrong root highlight in a book about
  // a Hebrew word is worse than none, so this never guesses.

  // Combining marks that belong to the letter before them: nikkud, dagesh, the
  // shin/sin dots, the rafe. NOT U+05BE maqaf, which is a hyphen and a character
  // in its own right, and not U+05C0/U+05C3 which are punctuation.
  function isHebMark(cp) {
    return (cp >= 0x0591 && cp <= 0x05BD) || cp === 0x05BF ||
           cp === 0x05C1 || cp === 0x05C2 || cp === 0x05C4 ||
           cp === 0x05C5 || cp === 0x05C7;
  }
  function isHebLetter(cp) { return cp >= 0x05D0 && cp <= 0x05EA; }

  // -> [{ base: 'פ', text: 'פְּ' }, ...] — one entry per written letter, each
  // carrying its own points, so a letter can be lit or dimmed as a single object.
  function hebClusters(word) {
    var out = [];
    for (var i = 0; i < word.length; i++) {
      var cp = word.charCodeAt(i);
      if (isHebMark(cp) && out.length) { out[out.length - 1].text += word[i]; continue; }
      out.push({ base: word[i], text: word[i] });
    }
    return out;
  }

  // Greedy left-to-right subsequence match. The string is in logical order, which
  // for Hebrew is the order the letters are written, so a root always appears in
  // order if it appears at all. Returns null unless EVERY root letter was found.
  function rootFlags(clusters, root) {
    if (!root) return null;
    var flags = new Array(clusters.length), r = 0;
    for (var i = 0; i < clusters.length && r < root.length; i++) {
      if (!isHebLetter(clusters[i].base.charCodeAt(0))) continue;
      if (clusters[i].base === root[r]) { flags[i] = true; r++; }
    }
    return r === root.length ? flags : null;
  }

  function inkGlyphs(word, root) {
    var clusters = hebClusters(word);
    var flags = rootFlags(clusters, root);
    return clusters.map(function (c, i) {
      if (c.text === ' ') return ' ';
      var cls = 'lex-g' + (flags && flags[i] ? ' is-root' : '');
      return '<span class="' + cls + '">' + esc(c.text) + '</span>';
    }).join('');
  }

  // THE FILTER. Fifty plates is a lot to scroll if you came looking for one word.
  // Real <button>s with aria-pressed, not links and not a <select> — the state is
  // "which one of these is on", which is what aria-pressed is for, and a select on
  // a phone opens a modal wheel for what is a one-tap choice.
  //
  // Chapters with no words are not rendered as dead buttons. Every chapter has some
  // today, but the lexicon is data and that can change.
  // LANGUAGE IS A SECOND WAY IN, added 2026-08-29 (D14-E). The wall is short enough
  // to read now, which raises a question the eight-and-a-half-screen version could
  // not: chapter order is only ONE of the orders somebody wants. Two more were
  // already sitting in the data.
  // 🛑 STILL ONE FILTER AT A TIME. Chapter and language are both "which one of these
  // is on", so they share a single data-filter on the wall and a single pressed
  // button across both groups. Crossing them (chapter VII ∩ Greek) would need a
  // second state, a second empty case, and a reason — and there is no reason: the
  // Greek is only in the New Testament chapters anyway, so the cross is the language.
  var LANG_NAME = { he: 'Hebrew', grc: 'Greek', akk: 'Akkadian' };

  function filterRow(entries) {
    var seen = {}, order = [];
    entries.forEach(function (e) { if (!seen[e.ch]) { seen[e.ch] = 0; order.push(e); } seen[e.ch]++; });
    var btns = order.map(function (e) {
      return '<button type="button" class="lex-filter-btn" data-filter="' + esc(e.ch) + '"' +
        ' aria-pressed="false"><span class="visually-hidden">Chapter </span>' +
        (ROMAN[e.num] || e.num) +
        '<span class="lex-filter-n">' + seen[e.ch] + '</span></button>';
    }).join('');

    var langSeen = {}, langOrder = [];
    entries.forEach(function (e) {
      if (!langSeen[e.lang]) { langSeen[e.lang] = 0; langOrder.push(e.lang); }
      langSeen[e.lang]++;
    });
    var langBtns = langOrder.map(function (l) {
      return '<button type="button" class="lex-filter-btn" data-filter="lang:' + esc(l) + '"' +
        ' aria-pressed="false">' + esc(LANG_NAME[l] || l) +
        '<span class="lex-filter-n">' + langSeen[l] + '</span></button>';
    }).join('');

    return '<div class="lex-controls">' +
      '<div class="lex-filter" role="group" aria-label="Show one chapter, or one language">' +
        '<span class="lex-controls-label" aria-hidden="true">Show</span>' +
        '<button type="button" class="lex-filter-btn is-on" data-filter="all" aria-pressed="true">' +
          'All<span class="lex-filter-n">' + entries.length + '</span></button>' +
        btns +
        '<span class="lex-filter-sep" aria-hidden="true"></span>' +
        langBtns +
      '</div>' +
      // THE SORT. Chapter order is the book's order and stays the default, because
      // the lexicon is the back of THIS book before it is a dictionary. A–Z is how
      // you use a dictionary when you half-remember a word, which is the other half
      // of what this page is for. Two options, so two buttons — a <select> for a
      // binary choice opens a modal wheel on a phone for a one-tap decision.
      '<div class="lex-sort" role="group" aria-label="Order the words">' +
        '<span class="lex-controls-label" aria-hidden="true">Order</span>' +
        '<button type="button" class="lex-filter-btn is-on" data-sort="book" aria-pressed="true">' +
          'Chapter order</button>' +
        '<button type="button" class="lex-filter-btn" data-sort="az" aria-pressed="false">' +
          'A\u2013Z</button>' +
      '</div>' +
    '</div>';
  }

  // THE WALL, 2026-08-29. Fifty plates in a card grid was 8,439px — EIGHT AND A HALF
  // SCREENS of scrolling to look up one word — and a lexicon is a lookup, not a
  // reading. It is now what the closing page of a book about one word should be: a
  // page OF words. All fifty are set as type in one block, each one a real control,
  // and choosing one opens its entry BESIDE the wall in the apparatus column — the
  // same columns 10–12 the verse notes moved into on the same day. Two panels, the
  // shape a printed dictionary has: the headwords, and the article.
  //
  // 🛑 THE ENTRIES ARE ALL RENDERED, NOT TEMPLATED ON CLICK. Fifty small articles
  // cost nothing, and it means the ink-and-root animation is still plain CSS on live
  // type with markup built once — no string-building in an event handler, and every
  // entry keeps its own id so #lex-panim (the hero's word links to it) still lands.
  //
  // 🛑 THE DEFAULT SELECTION IS panim. An empty apparatus column beside a wall of
  // words reads as broken, and the one word the whole book is about is the right
  // thing to be showing when the reader arrives.
  function lexSlug(e) {
    return 'lex-' + e.t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  }

  // THE WALL CARRIES THE BOOK'S OWN WEIGHTING, 2026-08-30 (D15-B). The author asked
  // for the words to be sized by how often the book uses them. Measured first, and
  // the raw count turned out to be the wrong instrument — so this is the measurement
  // it was replaced with, and the reason is worth keeping next to the code:
  //
  // 🛑 RAW FREQUENCY WOULD HAVE PRINTED A LIE. Ten of the fifty entries are PHRASES
  // the book quotes in English and never transliterates — ya'er YHWH panav, baqqeshu
  // panai, ka-chalamish. They score ZERO against the prose. Sizing by the raw count
  // would have set ten of the book's load-bearing lines as the smallest type on the
  // wall, which is the opposite of true. The distribution is also not a gradient:
  // panim 45, ehyeh 11, then a flat field of 3s and 1s. Fifty sizes off that spread
  // is a tag cloud, which is the risk the design sheet flagged.
  //
  // THREE WEIGHTS, from two things the data already knows:
  //   3  panim — the word the whole book follows, and 45 mentions to one other word's 11
  //   2  a chapter's own mark (kind: 'mark'), or a word the prose says five or more times
  //   1  everything else
  // Five is measured, not guessed: it is the gap in the actual distribution — ehyeh
  // (11), ra'ah (6) and metamorphoo (6) sit above it and the next word down is 4.
  //
  // Multi-word entries take their weight from `kind` alone. A phrase has no token to
  // count and the marks among them are already weight 2, which is the right answer.
  var LEX_OFTEN = 5;
  function lexWeights(entries) {
    var counts = Object.create(null);
    var chapters = window.PANIM_CHAPTERS || [];
    // one walk, one tokenise, then fifty map reads — rather than fifty scans of the
    // whole manuscript. Measured at 9ms over the 362KB of prose.
    var prose = [];
    (function walk(v) {
      if (v == null) return;
      if (typeof v === 'string') { prose.push(v); return; }
      if (typeof v !== 'object') return;
      if (Array.isArray(v)) { for (var i = 0; i < v.length; i++) walk(v[i]); return; }
      for (var k in v) if (Object.prototype.hasOwnProperty.call(v, k)) walk(v[k]);
    })(chapters);
    var flat = lexNorm(prose.join(' ').replace(/<[^>]+>/g, ' '));
    var toks = flat.split(/[^a-z\u0370-\u03ff\u05d0-\u05ea]+/);
    for (var j = 0; j < toks.length; j++) {
      if (toks[j]) counts[toks[j]] = (counts[toks[j]] || 0) + 1;
    }
    var w = {};
    entries.forEach(function (e) {
      var t = lexNorm(e.t);
      var weight = 1;
      if (e.kind === 'mark') weight = 2;
      if (!/[\s-]/.test(t) && (counts[t] || 0) >= LEX_OFTEN) weight = 2;
      if (t === 'panim') weight = 3;
      w[lexSlug(e)] = weight;
    });
    return w;
  }
  // lower-cased, decomposed, marks stripped, apostrophes dropped — so ra'ah in the
  // lexicon and ra'ah in the prose are the same token whichever quote glyph is used.
  function lexNorm(s) {
    return String(s).toLowerCase().normalize('NFD')
      .replace(/[\u0300-\u036f\u0591-\u05c7]/g, '')
      .replace(/[\u2019\u2018'`]/g, '');
  }

  function renderLexicon() {
    var entries = window.PANIM_LEXICON || [];
    if (!entries.length) return '';

    // 🛑 NOTHING IS OPEN WHEN THE PAGE ARRIVES — 2026-08-30 (D22-A), the author's
    // "i really like when all the hebrew and greek words load up and i see them all
    // written ... the thing moving at the top actually hides that."
    // He was describing a fact: the entry was rendered OPEN, and on a phone it is
    // pinned over the wall, so the one moment the section is built for — fifty words
    // writing themselves — happened behind a panel. The default selection is now a
    // slug the wall CARRIES rather than a state it ships in: js/ui.js opens it on a
    // wide screen once the ink has finished, and never opens it on a phone, where
    // the entry sits in the wall itself and would push the words it is covering for.
    var defaultSlug = null;
    entries.forEach(function (e) { if (e.t === 'panim') defaultSlug = lexSlug(e); });
    if (!defaultSlug) defaultSlug = lexSlug(entries[0]);
    // what the chips and plates render WITH. Nothing. The wall keeps the name.
    var openSlug = null;

    var weights = lexWeights(entries);

    var chips = entries.map(function (e) {
      var heb = e.lang === 'he';
      var slug = lexSlug(e);
      var wordCls = heb ? '' : (e.lang === 'grc' ? ' is-greek' : ' is-roman');
      var on = slug === openSlug;
      // The word is the control's label and the transliteration rides under it, so a
      // reader who cannot read the script still has a way in — which is the whole
      // reason the wall works as an index rather than as fifty shapes.
      // data-lang and data-t are the two axes added 2026-08-29 (D14-E): the filter
      // row can now select a language, and the sort row can order the wall by
      // transliteration. Both read off the chip, so neither needs a second copy of
      // the array — the thing that gave the Listening Room a cream paper.
      return '<button type="button" class="lex-chip' + (on ? ' is-on' : '') + '"' +
        ' id="' + esc(slug) + '" data-lex="' + esc(slug) + '" data-ch="' + esc(e.ch) + '"' +
        ' data-lang="' + esc(e.lang) + '" data-t="' + esc(String(e.t).toLowerCase()) + '"' +
        ' data-weight="' + (weights[slug] || 1) + '"' +
        ' aria-pressed="' + (on ? 'true' : 'false') + '" aria-controls="lex-article">' +
        // 🛑 The space between the two spans is load-bearing. They are flex column
        // children so it collapses to nothing on screen, and without it the control's
        // accessible name is the two runs jammed together — "אֵל רֳאִיEl Ro'i".
        // Exactly the trap the verse citation hit on 2026-08-29.
        '<span class="lex-chip-word' + wordCls + '" lang="' + esc(e.lang) + '"' +
          (heb ? ' dir="rtl"' : '') + '>' + esc(e.w) + '</span> ' +
        '<span class="lex-chip-t">' + esc(e.t) + '</span>' +
      '</button>';
    // 🛑 JOINED ON A NEWLINE, NOT ON ''. The wall is justified type from 2026-08-30
    // (D15-A) and `text-align: justify` stretches the WHITE SPACE between inline
    // boxes. With the chips joined edge to edge there is no white space on the line,
    // so every line sets flush left and the justification silently does nothing.
    // The gap between words is this character, not a flex `gap`.
    }).join('\n');

    var articles = entries.map(function (e) {
      var heb = e.lang === 'he';
      var slug = lexSlug(e);
      var wordCls = heb ? '' : (e.lang === 'grc' ? ' is-greek' : ' is-roman');
      var lit = heb ? inkGlyphs(e.w, e.root) : esc(e.w);
      var roman = ROMAN[e.num] || e.num;
      // THE ROOT LINE, AND — SINCE 2026-08-29 (D14-F) — THE LINE THAT REPLACES IT.
      // Only 19 of the 50 entries carry a `root` the matcher can confirm against the
      // pointed form, and the matcher FAILS SAFE: a wrong root in a book about a
      // Hebrew word is worse than no root. That was correct and it stayed correct.
      // What changed is that one word now fills the apparatus column on its own, so
      // the absence is a hole the reader can see, and a hole invites the wrong guess
      // — that the entry is unfinished. It is not unfinished; the root is either not
      // the right idea for that word or it was never confirmed twice.
      // 🛑 Four different reasons, four different sentences. One catch-all line would
      // be a worse lie than silence: "no root" is true of a Greek verb and of a
      // six-word Hebrew clause for completely unrelated reasons.
      var rootLine;
      if (heb && rootFlags(hebClusters(e.w), e.root)) {
        rootLine = '<p class="lex-root-note">root <span class="lex-root-word" lang="he" dir="rtl">' +
          esc(e.root) + '</span></p>';
      } else if (heb && /[\s\u05be]/.test(e.w)) {
        // a space, or a maqqef (־) — the Hebrew hyphen that binds a phrase into one
        // accentual word. Either way it is more than one word and has more than one root.
        rootLine = '<p class="lex-root-note is-absent">No single root. This is a phrase.</p>';
      } else if (e.lang === 'grc') {
        rootLine = '<p class="lex-root-note is-absent">Greek builds from stems, not from a ' +
          'three-letter root.</p>';
      } else if (e.lang === 'akk') {
        rootLine = '<p class="lex-root-note is-absent">Akkadian, not Hebrew. No root ' +
          'is given here.</p>';
      } else {
        rootLine = '<p class="lex-root-note is-absent">No root shown. It was not ' +
          'confirmed in two sources, and a guess would be worse than a gap.</p>';
      }
      var on = slug === openSlug;
      return '<article class="lex-plate" data-lex-entry="' + esc(slug) + '"' +
        ' data-ch="' + esc(e.ch) + '" data-kind="' + esc(e.kind) + '"' +
        (on ? '' : ' hidden') + '>' +
        '<p class="lex-tag">' + (e.kind === 'mark'
            ? 'Chapter ' + roman + ' · its own word'
            : 'Chapter ' + roman) + '</p>' +
        '<div class="lex-word' + wordCls + '" lang="' + esc(e.lang) + '"' +
          (heb ? ' dir="rtl"' : '') + '><span class="lex-ink">' + lit + '</span></div>' +
        '<p class="lex-translit">' + esc(e.t) + '</p>' +
        rootLine +
        '<p class="lex-gloss">' + esc(e.g) + '</p>' +
        '<p class="lex-where"><span>' + esc(e.r) + '</span>' +
          '<a href="#' + esc(e.ch) + '">Chapter ' + roman + '</a></p>' +
      '</article>';
    }).join('');

    return '<section class="section" id="lexicon" data-ch="fw" aria-labelledby="lexicon-heading">' +
      '<div class="section-inner">' +
        // 🛑 THE HEAD IS THE NAME AND ONE LINE, 2026-08-30 (D19-A), the author's
        // "only keep Choose a word and it draws itself ... the other lexicon
        // nonsense is unnecessary. say the lexicon and then the info. let them
        // feel it."
        // What went: the count-title ("50 words, in the language they were written
        // in") and the provenance paragraph. Both described the section instead of
        // opening it, and the wall underneath is fifty words a reader can see and
        // count. The line that survives is the only one that tells you something
        // you cannot get by looking: that the word will DRAW ITSELF and then dim to
        // its root. It is an instruction for a thing about to happen, which is why
        // it earns its place where two paragraphs of description did not.
        //
        // ⚠️ THE MARGIN LABEL IS THE <h2>, the second .chapter-num on the site to
        // be one — the Index of Scripture was the first (D18-B) and the reasoning
        // is identical: aria-labelledby has to resolve, and the heading outline
        // cannot skip from the section to its h4 entries. .is-bare is the shared
        // class, so a third section doing this needs no new CSS.
        //
        // 🛑 "NOT ONE CHARACTER WAS TYPED FROM MEMORY" IS OFF THE SITE ENTIRELY, and
        // that is the right end for it. It went out of the Sources standfirst on
        // D18-A and out of here on D19-A, both on the author's "delete this", and I
        // checked the live DOM rather than assuming it had landed somewhere: it is
        // in neither section now. ⚠️ THE PROOF DID NOT GO WITH IT. The Sources page
        // still lists eleven works and what each one supplied, which is the evidence;
        // the sentence was only ever the boast on top of it. Do not restore it here.
        // If it ever comes back, it belongs on the page that can be checked.
        '<div class="lex-head is-bare">' +
          '<h2 class="chapter-num" id="lexicon-heading">The Lexicon</h2>' +
          '<div class="lex-standfirst">' +
            '<p class="lex-legend">Choose a word and it draws itself, right to left. ' +
            'Then everything that is not a root consonant dims.</p>' +
          '</div>' +
        '</div>' +
        '<div class="lex-body">' +
          '<div class="lex-wall" id="lex-wall" data-default="' + esc(defaultSlug) + '" role="group" ' +
            'aria-label="The ' + entries.length + ' words. Choose one to read its entry.">' +
            chips + '</div>' +
          // 🛑 THE CONTROLS SIT UNDER THE WALL, 2026-08-30 (D19-B), the author's
          // "put the hebrew filter roman numerals below the words". They are inside
          // .lex-body and in the WALL's columns, not the section's, so they land
          // under the words they filter rather than under the whole two-column
          // body. Above the wall they were the first thing in the section and read
          // as a toolbar you had to get past; under it they read as apparatus for a
          // block of type you have already seen — which is the order a printed
          // index uses, and the order the reader actually works in.
          // ⚠️ THE DOM ORDER IS THE TAB ORDER and that is the real reason this is
          // safe: the wall is what the section is for, so a keyboard reader now
          // reaches the words first and the filters after, instead of tabbing
          // through sixteen controls to get to the thing they control.
          filterRow(entries) +
          '<div class="lex-article" id="lex-article" aria-live="polite">' + articles + '</div>' +
        '</div>' +
      '</div></section>';
  }

  // ============================================================================
  // THE INDEX OF SCRIPTURE
  // A book that quotes 115 verses and annotates 113 of them has an index, and this
  // one did not. Everything it needs already existed: the citations are structured
  // data on the verse blocks in content/chapters.js, and every .verse-box already
  // carries an id.
  //
  // 🛑 BUILT AT RENDER TIME FROM PANIM_CHAPTERS, never from a generated file, and
  // that is the whole reason it is safe to link to block ids. Block ids MOVE on every
  // rebuild — it is why content/verse-notes.js keys on chapter + citation instead.
  // Here the anchor and the link are produced from the same array in the same pass,
  // so they cannot drift from each other. Do NOT "optimise" this into a checked-in
  // content/scripture.js: that is the exact file that would go stale silently.
  //
  // The two quotations in chapter V that carry no reference on purpose are absent
  // here, which is correct — an index lists what was cited.
  // ============================================================================

  // Canonical order, so the index reads like the back of a Bible rather than like a
  // computer's idea of alphabetical: Malachi before Matthew, not after.
  var CANON = [
    'Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth',
    '1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra',
    'Nehemiah','Esther','Job','Psalm','Psalms','Proverbs','Ecclesiastes','Song of Songs',
    'Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah',
    'Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi',
    'Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians',
    'Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians',
    '1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter',
    '1 John','2 John','3 John','Jude','Revelation'
  ];

  // "1 Samuel 3:10" -> { book: '1 Samuel', ch: 3, v: 10 }. The verse number is only
  // ever used to sort, so an en-dashed range sorts on the first verse it names.
  function parseRef(ref) {
    var m = String(ref).match(/^((?:[1-3]\s)?[A-Za-z][A-Za-z\s]*?)\s+(\d+):(\d+)/);
    if (!m) return null;
    return { book: m[1].trim(), ch: parseInt(m[2], 10), v: parseInt(m[3], 10) };
  }

  function renderScripture(chapters) {
    var byBook = {};
    var total = 0;
    chapters.forEach(function (c) {
      c.blocks.forEach(function (b) {
        if (b.type !== 'verse' || !b.ref) return;
        var pr = parseRef(b.ref);
        if (!pr) return;
        if (!byBook[pr.book]) byBook[pr.book] = [];
        byBook[pr.book].push({ ref: b.ref, id: b.id, num: c.num, ch: pr.ch, v: pr.v });
        total++;
      });
    });

    var books = Object.keys(byBook).sort(function (a, b) {
      var ia = CANON.indexOf(a), ib = CANON.indexOf(b);
      // anything the canon list does not name sorts to the end, alphabetically,
      // rather than silently to the front as index -1 would do
      if (ia === -1 && ib === -1) return a < b ? -1 : 1;
      if (ia === -1) return 1;
      if (ib === -1) return -1;
      return ia - ib;
    });
    if (!books.length) return '';

    var rows = books.map(function (book) {
      var list = byBook[book].slice().sort(function (a, b) {
        return a.ch - b.ch || a.v - b.v;
      });
      var seen = {};
      var cites = list.filter(function (e) {
        // the same verse quoted in two chapters earns two entries; the same verse
        // quoted twice in ONE chapter earns one
        var k = e.ref + '|' + e.num;
        if (seen[k]) return false;
        seen[k] = 1;
        return true;
      }).map(function (e) {
        // 🛑 THE BOOK NAME IS ITS OWN SPAN, 2026-08-30 (D20-C), and that is the
        // whole mobile redesign of this list. Every row printed "Genesis 3:7" under
        // a heading that already said GENESIS — eight characters of repetition on
        // each of 151 rows, which on a 362px phone is most of the row.
        // ⚠️ IT IS HIDDEN VISUALLY, NEVER WITH display:none. A screen reader reading
        // the citation list out of context needs the book; `display:none` and
        // `visibility:hidden` both take it out of the accessibility tree, so the
        // phone rule uses the clip-path visually-hidden pattern instead. The link's
        // accessible name is "Genesis 3:7, chapter IX" at every width.
        return '<li class="si-cite">' +
          '<a href="#' + esc(e.id) + '">' +
            '<span class="si-ref"><span class="si-ref-bk">' + esc(book) + ' </span>' +
              esc(String(e.ref).slice(book.length).replace(/^\s+/, '')) + '</span>' +
            '<span class="si-ch" aria-hidden="true">' + (ROMAN[e.num] || e.num) + '</span>' +
            '<span class="visually-hidden">, chapter ' + (ROMAN[e.num] || e.num) + '</span>' +
          '</a></li>';
      }).join('');
      return '<div class="si-book">' +
        '<h3 class="si-book-name">' + esc(book) + '</h3>' +
        '<ul class="si-list">' + cites + '</ul>' +
      '</div>';
    }).join('');

    return '<section class="section" id="scripture" data-ch="fw" aria-labelledby="scripture-heading">' +
      '<div class="section-inner">' +
        // 🛑 THE HEAD IS ONE LINE NOW, 2026-08-30 (D18-B), the author's "delete
        // this" on the title. It ran the whole standfirst pattern — a count, a
        // second count and a sentence about ordering — over an index whose
        // ordering is self-evident the moment you look at it: Genesis, Exodus,
        // Leviticus. The section says its name and then does its job.
        //
        // ⚠️ THE MARGIN LABEL IS THE <h2> NOW, NOT A <span>. Deleting the title
        // and leaving `aria-labelledby="scripture-heading"` pointing at nothing
        // would have left the section unnamed to a screen reader AND put a hole
        // in the heading outline between The Lexicon (h2) and the book names
        // inside this section (h3). So the label that was always there takes the
        // id and the element. The Lexicon does the same thing (D19-A) and shares
        // .is-bare with it; those two are the only .chapter-num on the site that
        // are headings, which is why it is written down rather than left to be found.
        '<div class="si-head is-bare">' +
          '<h2 class="chapter-num" id="scripture-heading">Index of Scripture</h2>' +
        '</div>' +
        '<div class="si-books">' + rows + '</div>' +
      '</div></section>';
  }

  // NAMES AND PLACES — the index a reader has and cannot do, 2026-08-30 (D15-F).
  //
  // There was an index of verses and an index of words, and no way to find MOSES.
  // Search covers it, but search is a thing you have to think to open; an index is a
  // thing you browse, and browsing is how you find the entry you did not know to
  // look for.
  //
  // 🛑 THE OCCURRENCES ARE MEASURED, NOT TYPED. content/names.js says who and where
  // the index covers and nothing else; the chapter numerals below come from scanning
  // the real blocks. A name whose forms appear nowhere renders nothing at all rather
  // than an entry pointing at a page that does not exist — the same fail-safe the
  // lexicon's root matcher uses, and the reason this index cannot drift from the
  // manuscript the way a hand-kept list would.
  //
  // ONE LINK PER CHAPTER, not one per mention. Moses is in 103 paragraphs; an entry
  // listing 103 links is a wall, and the reader's real question is "which chapters
  // is he in, and take me to the first one." So each chapter contributes one numeral
  // and it lands on the FIRST block in that chapter that names him.
  function nameOccurrences(chapters, entry) {
    var forms = entry.forms || [];
    if (!forms.length) return [];
    // longest form first, so "Ketef Hinnom" wins over "Hinnom" on the same block
    var ordered = forms.slice().sort(function (a, b) { return b.length - a.length; });
    var res = ordered.map(function (f) {
      // \b would not fire after an apostrophe, and the possessive is handled here
      // rather than being listed twice in the data
      return new RegExp('(^|[^A-Za-z])' + f.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
        '(\u2019s|\u2019|\'s|\'|)(?![A-Za-z])');
    });
    var hits = [];
    chapters.forEach(function (c) {
      var found = null;
      c.blocks.some(function (b) {
        if (b.type !== 'p' && b.type !== 'verse') return false;
        if (!b.id) return false;
        // 🛑 A VERSE BLOCK HAS NO `html`. tools/build-chapters.py stores a verse as
        // `lines: []` and a paragraph as `html: ''` — two different shapes, and the
        // first version of this read `b.html` only, so every name that stands in a
        // QUOTED VERSE and nowhere else in that chapter was invisible to the index.
        // Found 2026-08-30 while converting a paragraph in ch. VI into a verse: the
        // block went quiet on the same day it changed type, which is what surfaced it.
        var t = (b.html || (b.lines ? b.lines.join(' ') : '')).replace(/<[^>]+>/g, ' ');
        var any = res.some(function (r) { return r.test(t); });
        if (any) { found = b.id; return true; }
        return false;
      });
      if (found) hits.push({ num: c.num, id: found });
    });
    return hits;
  }

  function nameSlug(n) {
    return 'name-' + String(n).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  }
  // What renderNames actually found, handed on so js/search.js can offer the index
  // entry without re-scanning the manuscript for fifty-eight names. It is filled at
  // render time and read off window.PANIM_RENDERED, which is the same contract
  // BACK_MATTER uses — one scan, one truth.
  var NAME_HITS = [];

  function renderNames(chapters) {
    var entries = window.PANIM_NAMES || [];
    if (!entries.length) return '';

    var live = [];
    entries.forEach(function (e) {
      var hits = nameOccurrences(chapters, e);
      if (hits.length) live.push({ e: e, hits: hits });
    });
    if (!live.length) return '';

    live.sort(function (a, b) { return a.e.name.localeCompare(b.e.name); });

    NAME_HITS = live.map(function (r) {
      return {
        name: r.e.name, note: r.e.note || '', id: nameSlug(r.e.name),
        chapters: r.hits.map(function (h) { return h.num; })
      };
    });

    // grouped by initial, the way an index is read — you go to the letter first
    var byLetter = {};
    live.forEach(function (r) {
      var L = r.e.name.charAt(0).toUpperCase();
      (byLetter[L] = byLetter[L] || []).push(r);
    });


    var rows = Object.keys(byLetter).sort().map(function (L) {
      var items = byLetter[L].map(function (r) {
        var cites = r.hits.map(function (h) {
          return '<li class="ni-cite"><a href="#' + esc(h.id) + '">' +
            '<span class="ni-num" aria-hidden="true">' + (ROMAN[h.num] || h.num) + '</span>' +
            '<span class="visually-hidden">Chapter ' + (ROMAN[h.num] || h.num) + '</span>' +
          '</a></li>';
        }).join('');
        // 🛑 NO PERSON / PLACE BADGE, dropped 2026-08-30 (D17-B). Every entry used to
        // print its kind in tracked uppercase beside the name, and beside MOSES or
        // JESUS that badge is comedy: it labels what the reader already knows and
        // adds a second piece of type to every one of fifty-eight entries. The split
        // between people and places is no longer stated anywhere on the page, and
        // does not need to be: the note under each name says which it is by saying
        // what it is. Every entry in content/names.js has one — see the header there.
        // 🛑 THE ENTRY CARRIES AN ID AS OF D22-D, and it is what makes the index
        // linkable from anywhere. js/search.js offers the index entry as a result
        // (the author's "do it", round seventeen §4 #4) and it needs somewhere to
        // send the reader. Built from the name, the same way the lexicon slug is,
        // and prefixed so it can never collide with a chapter or block id.
        return '<div class="ni-entry" id="' + esc(nameSlug(r.e.name)) + '">' +
          '<h4 class="ni-name">' + esc(r.e.name) + '</h4>' +
          (r.e.note ? '<p class="ni-note">' + esc(r.e.note) + '</p>' : '') +
          '<ul class="ni-list">' + cites + '</ul>' +
        '</div>';
      }).join('');
      return '<div class="ni-letter">' +
        '<h3 class="si-book-name">' + L + '</h3>' +
        '<div class="ni-entries">' + items + '</div>' +
      '</div>';
    }).join('');

    return '<section class="section" id="names" data-ch="fw" aria-labelledby="names-heading">' +
      '<div class="section-inner">' +
        // 🛑 BARE HEAD, 2026-08-30 (D20-A), the author's "delete that title its ugly
        // and names and places probably needs a proper title after. bigger text."
        // Third section to do this after Scripture (D18-B) and the Lexicon (D19-A),
        // and the last of the four — so the back matter is now ONE shape: the
        // section's name, then the section. That answers round seventeen's D3 by
        // building it rather than by putting it to him as an option again.
        // The second half of his note is the part that matters: a bare head is only
        // good if the name left standing is a TITLE. At --ap-sm it was a 10px margin
        // label doing a title's job. See .si-head.is-bare .chapter-num in
        // css/components.css — all three bare heads got the size in one place.
        '<div class="si-head is-bare">' +
          '<h2 class="chapter-num" id="names-heading">Names and Places</h2>' +
        '</div>' +
        '<div class="ni-body">' + rows + '</div>' +
      '</div></section>';
  }

  // WHERE THESE CAME FROM — the sources page, 2026-08-30 (D15-D).
  //
  // 🛑 THE SECTION EXISTS TO CLOSE A GAP THE LEXICON OPENED. Its standfirst claims
  // "not one character was typed from memory" and then names no source. A claim that
  // cannot be checked is decoration; this is the check. It is also, of the four
  // back-matter candidates on the round-fourteen sheet, the one that buys the most
  // for a sceptical reader — it is the thing that makes the rest of the apparatus
  // worth trusting.
  //
  // ⚠️ A ROW MARKED `status: 'unconfirmed'` PRINTS ITS CLAIM AND WITHHOLDS ITS
  // CITATION, and says so on the page. That is deliberate and it is the whole ethic
  // of the section: a page built to prove nothing was typed from memory must not
  // itself contain a citation typed from memory. The gap is visible, in the reader's
  // sight, rather than papered over with a plausible volume number.
  function renderSources() {
    var groups = window.PANIM_SOURCES || [];
    if (!groups.length) return '';

    // the count of works is no longer printed (D20-A cut the title that carried it),
    // and it is not computed either — an unread variable is a stale one waiting to
    // happen. The number lives in BACK_MATTER's contents row, which reads the real
    // groups at render time.
    var open = 0;
    groups.forEach(function (g) {
      (g.items || []).forEach(function (it) { if (it.status === 'unconfirmed') open++; });
    });

    var body = groups.map(function (g) {
      var items = (g.items || []).map(function (it) {
        var unconfirmed = it.status === 'unconfirmed';
        return '<article class="src-item' + (unconfirmed ? ' is-open' : '') + '">' +
          '<h4 class="src-title">' + esc(it.title) + '</h4>' +
          '<p class="src-who">' + esc(it.who) + '</p>' +
          '<p class="src-what">' + esc(it.what) + '</p>' +
          (it.where
            ? '<p class="src-where">' + esc(it.where) + '</p>'
            : '') +
          (unconfirmed
            // said outright, in the reader's sight. The alternative is a citation
            // nobody checked, which is the thing this page is against.
            ? '<p class="src-flag">Citation not yet filled in here. The excavation and ' +
              'the objects are published; this page will not print a volume or a page ' +
              'number it has not read.</p>'
            : '') +
        '</article>';
      }).join('');
      return '<div class="src-group">' +
        '<h3 class="src-group-head">' + esc(g.group) + '</h3>' +
        (g.note ? '<p class="src-group-note">' + esc(g.note) + '</p>' : '') +
        '<div class="src-items">' + items + '</div>' +
      '</div>';
    }).join('');

    return '<section class="section" id="sources" data-ch="fw" aria-labelledby="sources-heading">' +
      '<div class="section-inner">' +
        // 🛑 THE FOURTH AND LAST BARE HEAD, 2026-08-30 (D20-A).
        // The author cut three of these in one evening — Scripture, the Lexicon,
        // then Names and Places — each time for the same reason, and his words on
        // the last one were "delete that title its ugly." He did not name this one.
        // I finished it anyway and it is worth saying why: "11 works, and what each
        // one supplied" is the SAME CONSTRUCTION as the three he cut, and leaving it
        // standing would have shipped one section of the back matter with a 10px
        // label and a count-title beside three with a real title and neither.
        // ⚠️ IT IS ONE LINE TO PUT BACK. Round seventeen D3 asked him whether all
        // four should match; three of four now do, so this is finishing a pattern he
        // set rather than guessing at one. If he wanted the count kept, restoring
        // this h2 and dropping .is-bare is the whole revert.
        //
        // .chapter-num, the component every other back-matter head uses — NOT a
        // new class. The first draft invented .section-label, which was defined
        // nowhere, so the label fell out of the margin column and set as body serif.
        // The margin label is SHORT ("The Sources"); the long name lives in
        // BACK_MATTER, where the contents and the nav read it.
        '<div class="lex-head is-bare">' +
          '<h2 class="chapter-num" id="sources-heading">The Sources</h2>' +
          (open
            ? '<div class="lex-standfirst">' +
                '<p class="lex-legend">' + open + ' of them ' + (open === 1 ? 'is' : 'are') +
                ' listed with the citation still open, and marked as such below. ' +
                'A page built to show its working does not get to guess at its own.</p>' +
              '</div>'
            : '') +
        '</div>' +
        '<div class="src-body">' + body + '</div>' +
      '</div></section>';
  }

  // Ch.8's tearing hairline (§8.4): the paragraph whose text contains "torn in two" gets a
  // .tear-line sibling that motion.js animates once, on scroll-into-view.
  function maybeTearLine(chapterId, plainText) {
    if (chapterId === 'ch08' && plainText.indexOf('torn in two') !== -1) {
      return '<span class="tear-line" aria-hidden="true"></span>';
    }
    return '';
  }

  // OPENING PLATE (Direction B). The chapter's first image used to be a graded
  // backdrop with the title sitting on top of it. It is now a plate that owns the
  // full width of the page with nothing laid over it, and the title lands on paper
  // underneath. That single inversion is most of the design: a photograph stops
  // being a texture behind the words and becomes the thing you are looking at.
  // With no image supplied the chapter simply opens with its title — no empty frame.
  // The "PLATE I / PLATE II" label was dropped 2026-08-28: a plate number is
  // apparatus for a book with a list of plates in the back matter, and this has
  // no such list — the numeral told the reader nothing they could use, and it
  // put a second roman numeral beside the chapter's own. The caption and its
  // reference stay; they say what the picture is and where it sits in the text.
  function renderPlate(slotId) {
    var img = window.PANIM_IMAGES ? window.PANIM_IMAGES[slotId] : null;
    if (!img || !img.src) return '';
    // The caption carries an optional `ref` — a scripture reference or a locator. A
    // plate in a book earns its place by telling you WHERE you are, not just what
    // you are looking at, and it sends the reader back into the text.
    var caption = (img.caption || img.ref)
      ? '<figcaption class="plate-caption">' +
          '<span class="plate-text">' + esc(img.caption || '') +
            (img.ref ? '<span class="plate-ref">' + esc(img.ref) + '</span>' : '') +
          '</span>' +
        '</figcaption>'
      : '';
    // the image lives inside .plate-frame, which is the clipping box. The parallax
    // in motion.js scales the image past 100%, and without a frame to crop it the
    // overflow paints straight over the caption underneath.
    return '<figure class="plate reveal" data-slot="' + esc(slotId) + '">' +
      '<div class="plate-frame"><picture>' + avifSource(slotId, PLATE_SIZES) +
        '<img src="' + esc(img.src) + '" alt="' + esc(img.alt || '') +
        '" loading="lazy" decoding="async"></picture></div>' +
      caption + '</figure>';
  }

  // CONTENTS. Ten chapters and, before this, the only ways in were the numeral strip
  // in the running head and scrolling. A book opens on its contents page; so does this.
  // Durations come from content/audio-manifest.js (voiceDur, seconds) — the same
  // numbers the player uses, so they cannot drift out of sync with the audio.
  // ============================================================================
  // THE BACK MATTER, AND THE ONE LIST BOTH CONTENTS SURFACES READ
  // 🛑 Until 2026-08-29 neither contents listed any of this. The running head's panel
  // (js/ui.js buildNavToc) and the contents section on the page both stopped at
  // chapter X, so What Comes Back, the Lexicon and the Index of Scripture were
  // reachable only by scrolling — and the book is 262,798px tall. Three finished
  // apparatus sections, no way in but the scroll bar or a lucky search.
  // Defined once here and read by BOTH surfaces (ui.js gets it off PANIM_RENDERED),
  // because two hand-kept copies of a list is how the dawn arc got its cream room.
  // `count` is filled at render time from the real thing, never typed.
  var BACK_MATTER = [
    // 🛑 THIS ORDER IS THE PAGE'S ORDER (D19-C). The Lexicon is first because it is
    // the one a reader opens mid-book; What Comes Back is a rereading and spoils the
    // payoffs. If you move a section in renderAll, move it here in the same commit.
    { id: 'lexicon',   title: 'The Lexicon',       note: 'every word the book turns on, in its own language' },
    { id: 'thread',    title: 'What Comes Back',   note: 'what each chapter planted, and where it paid off' },
    { id: 'scripture', title: 'Index of Scripture', note: 'every verse quoted, in the order a Bible keeps them' },
    { id: 'names',     title: 'Names and Places', note: 'every person and place the book names, and where to find them' },
    // 🛑 "The Sources", and it must match the <h2> renderSources prints — 2026-08-30
    // (D21-C), the author's "we dont need two names for sources". This row said
    // "Where These Came From" while the section called itself "The Sources", so the
    // contents and the running head sent a reader to a heading with a different name
    // on it. One thing, one name. If the section's title ever changes, change it here
    // in the same commit.
    { id: 'sources',   title: 'The Sources', note: 'the texts, the lexica and the translation this book stands on' }
  ];

  function backMatter() {
    var t = (window.PANIM_THREAD || []).length;
    var l = (window.PANIM_LEXICON || []).length;
    var v = 0;
    (window.PANIM_CHAPTERS || []).forEach(function (c) {
      c.blocks.forEach(function (b) { if (b.type === 'verse' && b.ref) v++; });
    });
    var counts = {
      thread: t ? t + ' threads' : '',
      lexicon: l ? l + ' words' : '',
      scripture: v ? v + ' verses' : '',
      names: (function () {
        var n = (window.PANIM_NAMES || []).length;
        return n ? n + ' names' : '';
      })(),
      sources: (function () {
        var n = 0;
        (window.PANIM_SOURCES || []).forEach(function (g) { n += (g.items || []).length; });
        return n ? n + ' works' : '';
      })()
    };
    return BACK_MATTER.map(function (b) {
      var o = { id: b.id, title: b.title, note: b.note, count: counts[b.id] || '' };
      return o;
    });
  }

  function renderContents(chapters) {
    var audio = window.PANIM_AUDIO || {};
    var rows = chapters.map(function (ch) {
      var a = audio[ch.id];
      var mins = a && a.voiceDur ? Math.round(a.voiceDur / 60) + ' min' : '';
      return '<a class="toc-row" href="#' + esc(ch.id) + '">' +
        '<span class="toc-num">' + ROMAN[ch.num] + '</span>' +
        '<span class="toc-body">' +
          '<span class="toc-title">' + esc(ch.title) + '</span>' +
          '<span class="toc-hook">' + esc(ch.hook) + '</span>' +
        '</span>' +
        '<span class="toc-dur">' + mins + '</span>' +
      '</a>';
    }).join('');

    var total = chapters.reduce(function (n, ch) {
      var a = audio[ch.id]; return n + (a && a.voiceDur ? a.voiceDur : 0);
    }, 0);
    var hrs = Math.floor(total / 3600), rem = Math.round((total % 3600) / 60);

    // ONE LINE, 2026-08-28. The section is now the words "Table of Contents" and
    // nothing else until it is tapped: no label, no chapter count, no running time
    // visible while it is closed. Everything below appears on open.
    // FOLDED WHOLE, earlier the same day. Folding only the standfirsts was the wrong cut: the
    // list still ran ~700px of index between the jacket and chapter I, and the thing
    // the author objected to was the block itself, not its height. The contents are
    // reachable from two other places that are always on screen — the Contents toggle
    // in the running head and the chapters sheet in the player — so on the page it is
    // now one line of apparatus that opens on demand, descriptions and all.
    // js/ui.js remembers the choice.
    return '<section class="section" id="contents">' +
      '<div class="section-inner">' +
        '<div class="toc-head">' +
          '<button type="button" class="toc-expand" id="toc-expand" ' +
            'aria-expanded="false" aria-controls="toc-list">Table of Contents</button>' +
          '<span class="toc-total">' + chapters.length + ' chapters &middot; ' +
            (hrs ? hrs + ' hr ' : '') + rem + ' min</span>' +
        '</div>' +
        '<nav class="toc" id="toc-list" aria-label="Table of contents">' + rows +
          backMatter().map(function (b) {
            return '<a class="toc-row toc-back" href="#' + esc(b.id) + '">' +
              '<span class="toc-num" aria-hidden="true">&middot;</span>' +
              '<span class="toc-body">' +
                '<span class="toc-title">' + esc(b.title) + '</span>' +
                '<span class="toc-hook">' + esc(b.note) + '</span>' +
              '</span>' +
              '<span class="toc-dur">' + esc(b.count) + '</span>' +
            '</a>';
          }).join('') +
        '</nav>' +
      '</div></section>';
  }

  function plainText(html) { return String(html || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim(); }

  function hookDuplicatesOpening(chapter) {
    var hook = plainText(chapter.hook);
    if (!hook) return true;
    for (var i = 0; i < chapter.blocks.length; i++) {
      if (chapter.blocks[i].type !== 'p') continue;
      return plainText(chapter.blocks[i].html).indexOf(hook) === 0;
    }
    return false;
  }

  function renderChapter(chapter) {
    var out = [];
    var dropCapDone = false;
    var plateHtml = '';
    var plateSlot = null;
    if (chapter.blocks.length && chapter.blocks[0].type === 'slot') {
      plateHtml = renderPlate(chapter.blocks[0].slot);
      if (plateHtml) plateSlot = chapter.blocks[0].slot;  // consumed: skip in flow
    }
    out.push('<section class="section chapter' + (plateHtml ? ' has-plate' : '') +
             '" id="' + chapter.id + '" data-ch="' + chapter.num + '">');
    out.push(plateHtml);
    out.push('<div class="section-inner">');
    out.push('<header class="chapter-header reveal">');
    // numeral and Hebrew mark share the margin column as one stack, so the mark sits
    // just under the numeral instead of dropping to a second grid row below the
    // whole title block.
    // Each chapter's own word, from content/marks.js — the openings all used to
    // show the same hardcoded PANIM_HEB. Hebrew is rtl and gets grapheme-split so
    // the combining nikkud stay attached; Greek is ltr and needs neither. Falls
    // back to פָּנִים if a chapter has no entry.
    var mk = (window.PANIM_MARKS || {})[chapter.id];
    var markHtml;
    if (mk && mk.w) {
      var isHeb = mk.lang === 'he';   // anything else is Greek (lang 'grc'), set LTR in the serif
      var title = mk.t + ': ' + mk.g + ' (' + mk.r + ')';
      markHtml =
        '<div class="chapter-mark' + (isHeb ? '' : ' is-greek') + '" lang="' + esc(mk.lang) + '"' +
             (isHeb ? ' dir="rtl"' : '') +
             ' tabindex="0" role="note"' +
             ' aria-label="' + esc(title) + '"' +
             ' data-mark-term="' + esc(mk.t) + '"' +
             ' data-mark-ref="' + esc(mk.r) + '"' +
             // reuses the existing #gloss-card tooltip rather than a second one
             ' data-gloss-text="' + esc(title) + '">' +
          (isHeb ? hebSpans(mk.w) : esc(mk.w)) +
        '</div>';
    } else {
      markHtml = '<div class="chapter-mark" lang="he" dir="rtl" aria-hidden="true">' +
        hebSpans(PANIM_HEB) + '</div>';
    }
    out.push('<div class="chapter-margin">' +
      '<span class="chapter-num">Chapter ' + ROMAN[chapter.num] + '</span>' +
      markHtml +
    '</div>');
    out.push('<div class="chapter-titleblock">');
    out.push('<h2 class="chapter-title">' + esc(chapter.title) + '</h2>');
    // The hook in content/chapters.js is the opening line of the chapter's own
    // first paragraph — in ch.I and ch.III it IS the whole first paragraph. The
    // old layout hid that (the hook sat centred under a huge title, and the prose
    // began a full screen lower, past a photograph); at this density the sentence
    // simply appears twice, four lines apart. So the hook is only set as a
    // standfirst when it is NOT how the prose already opens. No content is edited.
    if (!hookDuplicatesOpening(chapter)) {
      out.push('<p class="chapter-hook">' + esc(chapter.hook) + '</p>');
    }
    // TWO ACTIONS AT A CHAPTER HEAD, and the second one is why /c/NN/ exists.
    // Sharing #ch07 from this page unfurls as the whole book — one HTML file has
    // one set of Open Graph tags and cannot say anything else. /c/07/ is a stub
    // carrying chapter VII's own title, standfirst and plate that redirects into
    // the book (tools/gen-chapter-stubs.py). A free book moves by being sent to
    // people, so the link has to survive being sent.
    out.push('<div class="chapter-actions">');
    out.push('<button class="btn listen-from-here" data-listen-chapter="' + chapter.id + '">Listen from here</button>');
    out.push('<button type="button" class="btn btn-quiet share-chapter" data-share-chapter="' +
      esc(chapter.id) + '" data-share-num="' + chapter.num + '">Share this chapter</button>');
    out.push('</div>');
    out.push('</div>');
    out.push('</header>');

    var prayerBuffer = [];
    function flushPrayer() {
      if (prayerBuffer.length) {
        out.push('<div class="prayer-zone" data-prayer-zone="' + chapter.id + '">' + prayerBuffer.join('') + '</div>');
        prayerBuffer = [];
      }
    }

    chapter.blocks.forEach(function (b) {
      if (b.type === 'fivewords') return; // rendered separately, terminal section
      var html;
      if (b.type === 'slot') {
        if (b.slot === plateSlot) return; // consumed as the chapter's opening plate
        html = renderImageSlot(b.slot);
      } else if (b.type === 'p') {
        var tear = maybeTearLine(chapter.id, b._html.replace(/<[^>]+>/g, ''));
        // The drop cap goes on the first paragraph with enough text to wrap around
        // it. Chapter I opens on "Jerusalem, 1979." — a two-word paragraph, where a
        // three-line initial has nothing to sit beside and just floats.
        var cls = 'block-p reveal';
        if (!dropCapDone && b.zone !== 'prayer' && plainText(b._html).length >= 90) {
          cls += ' has-dropcap';
          dropCapDone = true;
        }
        html = '<p class="' + cls + '" id="' + esc(b.id) + '" data-cue-id="' + esc(b.id) + '">' + b._html + tear + '</p>';
      } else if (b.type === 'verse') {
        html = renderVerse(b, chapter.id);
      } else if (b.type === 'ref') {
        // A citation the manuscript sets on its own line, under the line it
        // cites — the prayer in ch. X is written this way throughout. It is
        // apparatus, not narration: the narrator never reads it, so it carries
        // no cue id and the follow-along steps straight over it.
        html = '<p class="block-ref">' + esc(b.ref) + '</p>';
      } else if (b.type === 'beat') {
        html = '<div class="divider-beat hairline" aria-hidden="true"></div>';
      } else if (b.type === 'swell') {
        // A swell is the same mark as a beat, held longer: the same rule, drawn
        // wider, with more air around it. Before this it carried no .hairline
        // and was only empty space, so a section break and a dropped paragraph
        // looked identical on the page.
        html = '<div class="divider-swell hairline" aria-hidden="true"></div>';
      } else {
        html = '';
      }
      if (b.zone === 'prayer') {
        prayerBuffer.push(html);
      } else {
        flushPrayer();
        out.push(html);
      }
    });
    flushPrayer();

    out.push('</div></section>');
    return out.join('');
  }

  // The hero photograph (PANIM_IMAGES.hero) is the opening plate: it takes the top
  // of the page on its own, with the title block set on paper beneath it. Nothing
  // is laid over the picture. With the slot empty the title block simply moves to
  // the top of the page and the site opens on type, which also works.
  function mountHero() {
    // the hero's Hebrew writes itself in, right to left, once on load
    var heb = document.querySelector('.hero-hebrew');
    if (heb && heb.textContent.trim()) {
      heb.innerHTML = hebSpans(heb.textContent.trim(), 90);
    }

    var img = window.PANIM_IMAGES ? window.PANIM_IMAGES.hero : null;
    var hero = document.getElementById('hero');
    if (!img || !img.src || !hero) return;
    var fig = document.createElement('figure');
    fig.className = 'hero-plate';
    // the hero is the LCP element: eager, high priority, and never lazy.
    fig.innerHTML = '<picture>' + avifSource('hero', PLATE_SIZES) +
      '<img src="' + esc(img.src) + '" alt="' + esc(img.alt || '') +
      '" fetchpriority="high" decoding="async"></picture>';
    hero.insertBefore(fig, hero.firstChild);
    hero.classList.add('has-hero-plate');
  }


  // ============================================================================
  // ONE QUIET ROW AT THE FOOT OF EACH APPARATUS SECTION — 2026-08-30 (D22-C)
  // The author's *"probably worth it??"* on round seventeen §4 #5, and his *"do it"*
  // on §4 #2, which asked for one link from the Lexicon to the page that proves it.
  // Both are the same missing thing, so this is one answer to two notes.
  //
  // Five finished sections, and until now each was a cul-de-sac: the Lexicon does
  // not mention the Sources, the Names index does not mention Scripture, and none of
  // them can get you back to the contents. Every way in was the running head or the
  // contents page, which means going UP through a 266,000px book to move sideways
  // between two things that are next to each other.
  //
  // 🛑 BUILT FROM BACK_MATTER, NOT TYPED. That array is already the one list both
  // contents surfaces read, and a sixth hand-kept copy of the section names is
  // exactly the drift D21-C closed. A section never links to itself; the row always
  // ends at the contents.
  // ⚠️ 44px, because they are touch targets and this project has a rule (D5). The
  // padding is what makes the height, so do not swap it for a line-height.
  // ============================================================================
  function backMatterLinks(root) {
    BACK_MATTER.forEach(function (b) {
      var sec = root.querySelector('#' + b.id);
      if (!sec) return;
      var links = BACK_MATTER.filter(function (o) { return o.id !== b.id; })
        .map(function (o) {
          return '<a class="bm-link" href="#' + o.id + '">' + esc(o.title) + '</a>';
        });
      links.push('<a class="bm-link is-back" href="#contents">Contents</a>');
      var nav = document.createElement('nav');
      nav.className = 'bm-links';
      nav.setAttribute('aria-label', 'The rest of the back matter');
      nav.innerHTML = links.join('');
      sec.appendChild(nav);
    });
  }

  function run() {
    var chapters = window.PANIM_CHAPTERS || [];
    var skippedGlossTerms = [];
    var html = [];

    html.push(renderContents(chapters));

    chapters.forEach(function (chapter) {
      // work on a private copy of html text per block so glossify never touches source data
      chapter.blocks.forEach(function (b) { if (b.type === 'p') b._html = b.html; });
      skippedGlossTerms = skippedGlossTerms.concat(glossify(chapter));
      html.push(renderChapter(chapter));
    });

    // five words: last block of ch10
    var ch10 = chapters[chapters.length - 1];
    var fw = ch10 && ch10.blocks[ch10.blocks.length - 1];
    if (fw && fw.type === 'fivewords') html.push(renderFiveWords(fw));

    // 🛑 THE LEXICON COMES FIRST, 2026-08-30 (D19-C), the author's "move greek
    // lexicon above the thread area that outlines the points coming back."
    // What Comes Back is a REREADING of the ten chapters: it only means anything to
    // someone who has finished them, and it spoils the payoffs for anyone who has
    // not. The Lexicon is a lookup — you use it mid-book, from a chapter, and the
    // chapter links point INTO it. So the thing you reach for while reading now
    // stands before the thing you read after finishing.
    // ⚠️ BACK_MATTER BELOW MUST MATCH THIS ORDER. It feeds the contents section and
    // the running head's panel, and a contents page that lists the back matter in a
    // different order from the page itself is worse than no contents.
    html.push(renderLexicon());
    html.push(renderThread());
    html.push(renderScripture(chapters));
    html.push(renderNames(chapters));
    html.push(renderSources());

    var root = document.getElementById('chapters-root');
    root.innerHTML = html.join('');
    backMatterLinks(root);

    mountHero();

    window.PANIM_RENDERED = {
      chapters: chapters,
      skippedGlossTerms: skippedGlossTerms,
      backMatter: backMatter(),
      nameHits: NAME_HITS,
      romanFor: function (n) { return ROMAN[n] || String(n); }
    };

    document.dispatchEvent(new CustomEvent('panim:rendered'));
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', run);
  } else {
    run();
  }
})();
