// PANIM_DERIVATIVES — GENERATED by tools/make-derivatives.sh. Do not hand-edit.
// slot id -> [{ w, src }] ascending, for the AVIF <source srcset> in js/render.js.
// The <img src> fallback stays the WebP in content/images.js.
window.PANIM_DERIVATIVES = {
  "ch01-scroll": [{ w: 640, src: "art/d/ch01-scroll-640.avif" }, { w: 940, src: "art/d/ch01-scroll-940.avif" }, { w: 1408, src: "art/d/ch01-scroll-1408.avif" }],
  "ch01-tomb": [{ w: 640, src: "art/d/ch01-tomb-640.avif" }, { w: 940, src: "art/d/ch01-tomb-940.avif" }, { w: 1408, src: "art/d/ch01-tomb-1408.avif" }],
  "ch02-storm": [{ w: 640, src: "art/d/ch02-storm-640.avif" }, { w: 940, src: "art/d/ch02-storm-940.avif" }, { w: 1408, src: "art/d/ch02-storm-1408.avif" }],
  "ch02-trees": [{ w: 640, src: "art/d/ch02-trees-640.avif" }, { w: 940, src: "art/d/ch02-trees-940.avif" }, { w: 1376, src: "art/d/ch02-trees-1376.avif" }],
  "ch03-mountain": [{ w: 640, src: "art/d/ch03-mountain-640.avif" }, { w: 940, src: "art/d/ch03-mountain-940.avif" }, { w: 1376, src: "art/d/ch03-mountain-1376.avif" }],
  "ch04-river": [{ w: 640, src: "art/d/ch04-river-640.avif" }, { w: 940, src: "art/d/ch04-river-940.avif" }, { w: 1408, src: "art/d/ch04-river-1408.avif" }],
  "ch05-bush": [{ w: 640, src: "art/d/ch05-bush-640.avif" }, { w: 940, src: "art/d/ch05-bush-940.avif" }, { w: 1408, src: "art/d/ch05-bush-1408.avif" }],
  "ch06-shine": [{ w: 640, src: "art/d/ch06-shine-640.avif" }, { w: 940, src: "art/d/ch06-shine-940.avif" }, { w: 1408, src: "art/d/ch06-shine-1408.avif" }],
  "ch07-gate": [{ w: 640, src: "art/d/ch07-gate-640.avif" }, { w: 940, src: "art/d/ch07-gate-940.avif" }, { w: 1408, src: "art/d/ch07-gate-1408.avif" }],
  "ch08-flint": [{ w: 640, src: "art/d/ch08-flint-640.avif" }, { w: 940, src: "art/d/ch08-flint-940.avif" }, { w: 1408, src: "art/d/ch08-flint-1408.avif" }],
  "ch08-veil": [{ w: 640, src: "art/d/ch08-veil-640.avif" }, { w: 940, src: "art/d/ch08-veil-940.avif" }, { w: 1408, src: "art/d/ch08-veil-1408.avif" }],
  "ch09-charcoal": [{ w: 640, src: "art/d/ch09-charcoal-640.avif" }, { w: 940, src: "art/d/ch09-charcoal-940.avif" }, { w: 1408, src: "art/d/ch09-charcoal-1408.avif" }],
  "ch09-emmaus": [{ w: 640, src: "art/d/ch09-emmaus-640.avif" }, { w: 940, src: "art/d/ch09-emmaus-940.avif" }, { w: 1408, src: "art/d/ch09-emmaus-1408.avif" }],
  "ch10-morning": [{ w: 640, src: "art/d/ch10-morning-640.avif" }, { w: 940, src: "art/d/ch10-morning-940.avif" }, { w: 1408, src: "art/d/ch10-morning-1408.avif" }],
  "ch10-veil-lift": [{ w: 640, src: "art/d/ch10-veil-lift-640.avif" }, { w: 940, src: "art/d/ch10-veil-lift-940.avif" }, { w: 1536, src: "art/d/ch10-veil-lift-1536.avif" }],
  "hero": [{ w: 640, src: "art/d/hero-640.avif" }, { w: 940, src: "art/d/hero-940.avif" }, { w: 1408, src: "art/d/hero-1408.avif" }],
};
