#!/usr/bin/env python3
"""Rewrite content/audio-manifest.js (the English one) from the files actually shipped.

    python3 tools/gen-audio-manifest.py

The page reads three fields: voiceDur (chapter length shown, read-along end, progress),
musicDur (fallback file length) and musicMB (the "Save for offline" size). All three
change when the recording does. voiceDur is the voice master's length, musicDur the
music master's -- both WAVs, as before -- and musicMB is the size of the .m4a in
audio/music/, the file a reader actually downloads. musicOffset is the music-alone lead-in
the player skips to find the voice: carried over unless MUSIC_LEAD is given (introoutro's
LEAD_IN -- 6.0 until 2026-09-24, then 10.0). It cannot be derived from the lengths: since
v95 each file ends 0.5 s after its own fade, so the tail differs by chapter. num, title and
the unused voiceMB are carried over unchanged.

    VOICEDIR=... MUSICDIR=... MUSIC_LEAD=10 python3 tools/gen-audio-manifest.py

VOICEDIR / MUSICDIR default to the v2 masters (2026-09-19).
"""
import json, os, re, wave

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VOICE = os.environ.get("VOICEDIR") or os.path.expanduser("~/Panim-audio/v2/voice-ship2")
MUSIC = os.environ.get("MUSICDIR") or os.path.expanduser("~/Panim-audio/v2/music-final2")
PATH = os.path.join(SITE, "content", "audio-manifest.js")
LEAD = os.environ.get("MUSIC_LEAD")


def wav_for(d, n):
    f = next(x for x in os.listdir(d) if re.match(rf"Chapter {n}[_ ]", x) and x.endswith(".wav"))
    return os.path.join(d, f)


def dur(path):
    with wave.open(path) as w:
        return w.getnframes() / w.getframerate()


src = open(PATH, encoding="utf-8").read()
head = ("// GENERATED by tools/gen-audio-manifest.py from the shipped masters and .m4a files. Do not hand-edit.\n"
        "// musicOffset: the music-alone lead-in before the voice, per chapter; voice timeline + musicOffset = music timeline.\n")
man = json.loads(src[src.index("{", src.index("window.PANIM_AUDIO")):src.rindex("}") + 1])
for cid, m in man.items():
    n = m["num"]
    m["voiceDur"] = round(dur(wav_for(VOICE, n)), 2)
    m["musicDur"] = round(dur(wav_for(MUSIC, n)), 2)
    if LEAD is not None: m["musicOffset"] = float(LEAD)
    lead = m["musicOffset"]
    assert m["musicDur"] > m["voiceDur"] + lead, f"{cid}: music shorter than lead-in + voice -- wrong masters"
    m["musicMB"] = round(os.path.getsize(os.path.join(SITE, "audio", "music", cid + ".m4a")) / 1e6, 1)
    print(f"{cid}  voice {m['voiceDur']:8.2f}s  music {m['musicDur']:8.2f}s  lead {lead:5.2f}s  {m['musicMB']:5.1f} MB")
open(PATH, "w", encoding="utf-8").write(head + "window.PANIM_AUDIO = " + json.dumps(man, indent=1, ensure_ascii=False) + ";\n")
