#!/bin/sh
# Cut responsive AVIF derivatives from every plate in art/, and write the
# manifest the renderer builds its srcset from.
#
# WHY. Every plate ships at 1408px to every device. A 402px phone downloads a
# 1408px WebP and paints it at 402. This makes the widths a `srcset` needs
# (640 / 940 / full) in AVIF, which is roughly half the bytes of the WebP at the
# same width. The original WebP stays as the <img src> fallback, so a browser
# without AVIF is exactly as well off as it was before.
#
# Uses sips, which ships with macOS: it reads WebP and writes AVIF, so there is
# no dependency to install (cwebp/avifenc/magick are NOT on this machine).
#
# 🛑 The top tier is the SOURCE's own width, never a fixed 1408. Two plates are
# 1376 wide and one is 1536; hard-coding 1408 would either upscale them or leave
# a 1376 plate with no tier above 940, which makes desktop WORSE than it is now.
# 🛑 The top tier is quality 65, the smaller two are 55. The big one is what a 2x
# desktop paints and the plates are already soft; do not drop it to match.
#
# Output: art/d/<name>-<width>.avif, plus content/derivatives.js (GENERATED —
# never hand-edit; re-run this instead).
# Replace a plate -> re-run this, AND re-run tools/make-cards.sh.
set -e
cd "$(dirname "$0")/.."
mkdir -p art/d

MANIFEST=content/derivatives.js
{
  echo "// PANIM_DERIVATIVES — GENERATED by tools/make-derivatives.sh. Do not hand-edit."
  echo "// slot id -> [{ w, src }] ascending, for the AVIF <source srcset> in js/render.js."
  echo "// The <img src> fallback stays the WebP in content/images.js."
  echo "window.PANIM_DERIVATIVES = {"
} > "$MANIFEST"

total_src=0
total_top=0

for f in art/*.webp; do
  [ -f "$f" ] || continue
  name=$(basename "$f" .webp)
  src_w=$(sips -g pixelWidth "$f" | awk '/pixelWidth/{print $2}')
  total_src=$((total_src + $(wc -c < "$f")))

  # 640 and 940 always; the top tier is the source's own width, deduped.
  widths=""
  for w in 640 940 "$src_w"; do
    case " $widths " in *" $w "*) continue ;; esac
    [ "$w" -le "$src_w" ] || continue
    widths="$widths $w"
  done

  rows=""
  for w in $widths; do
    out="art/d/$name-$w.avif"
    if [ "$w" -eq "$src_w" ]; then q=65; else q=55; fi
    sips -s format avif -s formatOptions $q --resampleWidth "$w" \
         "$f" --out "$out" >/dev/null
    bytes=$(wc -c < "$out")
    [ "$w" -eq "$src_w" ] && total_top=$((total_top + bytes))
    rows="$rows{ w: $w, src: \"$out\" }, "
    echo "$out  $bytes bytes"
  done

  printf '  "%s": [%s],\n' "$name" "${rows%, }" >> "$MANIFEST"
done

echo "};" >> "$MANIFEST"

echo "---"
echo "source WebP total:     $((total_src / 1024)) KB"
echo "AVIF at full width:    $((total_top / 1024)) KB"
echo "wrote $MANIFEST"
